### ISSUE TITLE
表达支持

### ISSUE THREAD

**Issue by yolo2013** [maundytime/Maofan#2]
表达一下对你的支付，很喜欢猫饭，fork下来也学习学习Swift。

**Comment by yolo2013** [comment]
clone下来运行的时候，配置页有个错误，看起来是我的开发者权限问题，
The app ID "com.maochang.Maofan" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

**Comment by maundytime** [comment]
好像是需要配置成自己的开发账号
